# Generated by Django 2.2.6 on 2021-11-29 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe_who_likes_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='who_likes_it',
            field=models.ManyToManyField(blank=True, related_name='favourite_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Кому понравилось'),
        ),
    ]
